### ISSUE TITLE
Fix db key names to human readable

### ISSUE THREAD

**Issue by oleksandr-horobets** [EugeneKopaev/BookLibrary#14]
CREATE TABLE `books_to_authors` (
  `BOOK_ID` BINARY(16) NOT NULL,
  `AUTHOR_ID` BINARY(16) NOT NULL,
  KEY `FK_gkqva844hy3bdgdkodri35g6o` (`AUTHOR_ID`),
  KEY `FK_1axc18jsubyvp41j2na9gk796` (`BOOK_ID`),
  CONSTRAINT `FK_1axc18jsubyvp41j2na9gk796` FOREIGN KEY (`BOOK_ID`) REFERENCES `books` (`ID`),
  CONSTRAINT `FK_gkqva844hy3bdgdkodri35g6o` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `authors` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

**Comment by EugeneKopaev** [comment]
done in commit 7cda1794680da0c06d838c6dc7f8221476fba065
